-- Snapshot of the 60 starter exercises; applied only when creating a database.

INSERT INTO exercises(id,name,name_key,measurement,load_convention,primary_muscle) VALUES
(1,'Barbell clean','barbell clean','repetitions','external',12),
(2,'Barbell power clean','barbell power clean','repetitions','external',12),
(3,'Barbell hang clean','barbell hang clean','repetitions','external',12),
(4,'Barbell hang power clean','barbell hang power clean','repetitions','external',12),
(5,'Barbell snatch','barbell snatch','repetitions','external',12),
(6,'Barbell power snatch','barbell power snatch','repetitions','external',12),
(7,'Barbell hang snatch','barbell hang snatch','repetitions','external',12),
(8,'Barbell hang power snatch','barbell hang power snatch','repetitions','external',12),
(9,'Barbell clean pull','barbell clean pull','repetitions','external',12),
(10,'Barbell pause clean pull','barbell pause clean pull','repetitions','external',12),
(11,'Barbell snatch pull','barbell snatch pull','repetitions','external',12),
(12,'Barbell snatch high pull','barbell snatch high pull','repetitions','external',12),
(13,'Barbell snatch panda pull','barbell snatch panda pull','repetitions','external',12),
(14,'Barbell squat','barbell squat','repetitions','external',9),
(15,'Barbell pause squat','barbell pause squat','repetitions','external',9),
(16,'Barbell box squat','barbell box squat','repetitions','external',9),
(17,'Barbell front squat','barbell front squat','repetitions','external',9),
(18,'Barbell pause front squat','barbell pause front squat','repetitions','external',9),
(19,'Barbell box front squat','barbell box front squat','repetitions','external',9),
(20,'Barbell overhead squat','barbell overhead squat','repetitions','external',9),
(21,'Barbell overhead press','barbell overhead press','repetitions','external',3),
(22,'Barbell push press','barbell push press','repetitions','external',3),
(23,'Barbell split jerk','barbell split jerk','repetitions','external',12),
(24,'Barbell behind the neck overhead press','barbell behind the neck overhead press','repetitions','external',3),
(25,'Barbell behind the neck push press','barbell behind the neck push press','repetitions','external',3),
(26,'Barbell bench press','barbell bench press','repetitions','external',1),
(27,'Barbell incline bench press','barbell incline bench press','repetitions','external',1),
(28,'Barbell bent over row','barbell bent over row','repetitions','external',2),
(29,'Barbell deadlift','barbell deadlift','repetitions','external',8),
(30,'Barbell romanian deadlift','barbell romanian deadlift','repetitions','external',10),
(31,'Barbell stiff leg deadlift','barbell stiff leg deadlift','repetitions','external',10),
(32,'Barbell split squat','barbell split squat','repetitions','external',9),
(33,'Barbell bulgarian split squat','barbell bulgarian split squat','repetitions','external',9),
(34,'Cable lat pull down','cable lat pull down','repetitions','external',2),
(35,'Cable row','cable row','repetitions','external',2),
(36,'Single arm cable row','single arm cable row','repetitions','external',2),
(37,'Cable chest fly','cable chest fly','repetitions','external',1),
(38,'Cable face pull','cable face pull','repetitions','external',3),
(39,'Cable tricep push down','cable tricep push down','repetitions','external',5),
(40,'Dumbbell rear delt reverse fly','dumbbell rear delt reverse fly','repetitions','external',3),
(41,'Dumbbell lateral raise','dumbbell lateral raise','repetitions','external',3),
(42,'Dumbbell front raise','dumbbell front raise','repetitions','external',3),
(43,'Dumbbell bench press','dumbbell bench press','repetitions','external',1),
(44,'Dumbbell incline bench press','dumbbell incline bench press','repetitions','external',1),
(45,'Dumbbell seated overhead press','dumbbell seated overhead press','repetitions','external',3),
(46,'Dumbbell single arm seated overhead press','dumbbell single arm seated overhead press','repetitions','external',3),
(47,'Dumbbell bicep curl','dumbbell bicep curl','repetitions','external',4),
(48,'Dumbbell hammer curl','dumbbell hammer curl','repetitions','external',4),
(49,'Machine leg extension','machine leg extension','repetitions','external',9),
(50,'Machine single leg extension','machine single leg extension','repetitions','external',9),
(51,'Machine leg curl','machine leg curl','repetitions','external',10),
(52,'Machine single leg curl','machine single leg curl','repetitions','external',10),
(53,'Machine hip abduction','machine hip abduction','repetitions','external',8),
(54,'Machine hip adduction','machine hip adduction','repetitions','external',13),
(55,'Machine standing calf raise','machine standing calf raise','repetitions','external',11),
(56,'Machine seated calf raise','machine seated calf raise','repetitions','external',11),
(57,'Dumbbell standing calf raise','dumbbell standing calf raise','repetitions','external',11),
(58,'Pull up','pull up','repetitions','added-bodyweight',2),
(59,'Push up','push up','repetitions','added-bodyweight',1),
(60,'Dips','dips','repetitions','added-bodyweight',1);

INSERT INTO exercise_equipment(exercise_id,equipment_id) VALUES
(1,1),
(2,1),
(3,1),
(4,1),
(5,1),
(6,1),
(7,1),
(8,1),
(9,1),
(10,1),
(11,1),
(12,1),
(13,1),
(14,1),
(15,1),
(16,1),
(17,1),
(18,1),
(19,1),
(20,1),
(21,1),
(22,1),
(23,1),
(24,1),
(25,1),
(26,1),
(27,1),
(28,1),
(29,1),
(30,1),
(31,1),
(32,1),
(33,1),
(34,5),
(35,5),
(36,5),
(37,5),
(38,5),
(39,5),
(40,2),
(41,2),
(42,2),
(43,2),
(44,2),
(45,2),
(46,2),
(47,2),
(48,2),
(49,6),
(50,6),
(51,6),
(52,6),
(53,6),
(54,6),
(55,6),
(56,6),
(57,2);

INSERT INTO exercise_secondary_muscles(exercise_id,muscle_id) VALUES
(14,2),
(14,7),
(14,8),
(15,2),
(15,7),
(15,8),
(16,2),
(16,7),
(16,8),
(17,2),
(17,7),
(17,8),
(18,2),
(18,7),
(18,8),
(19,2),
(19,7),
(19,8),
(20,2),
(20,3),
(20,7),
(20,8),
(21,5),
(22,5),
(22,8),
(22,9),
(24,5),
(25,5),
(25,8),
(25,9),
(26,3),
(26,5),
(27,3),
(27,5),
(28,3),
(28,4),
(28,6),
(29,2),
(29,6),
(29,7),
(29,9),
(29,10),
(30,2),
(30,6),
(30,8),
(31,2),
(31,6),
(31,8),
(32,2),
(32,7),
(32,8),
(33,2),
(33,7),
(33,8),
(34,3),
(34,4),
(34,6),
(35,3),
(35,4),
(35,6),
(36,3),
(36,4),
(36,6),
(37,3),
(38,2),
(40,2),
(41,2),
(42,1),
(43,3),
(43,5),
(44,3),
(44,5),
(45,5),
(46,5),
(46,7),
(47,6),
(48,6),
(51,11),
(52,11),
(58,4),
(58,6),
(59,3),
(59,5),
(60,3),
(60,5);
